export enum possiblePrerequisites {
    LEVEL_5 = 'can cast 5th level spells',
    LEVEL_6 = 'can cast 6th level spells',
    LEVEL_7 = 'can cast 7th level spells',
    LEVEL_8 = 'can cast 8th level spells',
    KNOWS_CONTAMINTED_LEVEL_1 = 'knows a contaminated spell of 1st level',
    KNOWS_CONTAMINTED_LEVEL_2 = 'knows a contaminated spell of 2nd level',
    KNOWS_CONTAMINTED_LEVEL_3 = 'knows a contaminated spell of 3rd level',
    KNOWS_CONTAMINTED_LEVEL_4 = 'knows a contaminated spell of 4th level',
    KNOWS_CONTAMINTED_LEVEL_5 = 'knows a contaminated spell of 5th level',
    KNOWS_CONTAMINTED_LEVEL_6 = 'knows a contaminated spell of 6th level',
    KNOWS_CONTAMINTED_LEVEL_7 = 'knows a contaminated spell of 7th level',
    CAST_CONTAMINATED_LEVEL_1 = 'has cast a contaminated spell of 1st level',
    CAST_CONTAMINATED_LEVEL_2 = 'has cast a contaminated spell of 2nd level',
    CAST_CONTAMINATED_LEVEL_3 = 'has cast a contaminated spell of 3rd level',
    CAST_CONTAMINATED_LEVEL_4 = 'has cast a contaminated spell of 4th level',
    CAST_CONTAMINATED_LEVEL_5 = 'has cast a contaminated spell of 5th level',
    CAST_CONTAMINATED_LEVEL_6 = 'has cast a contaminated spell of 6th level',
    CAST_CONTAMINATED_LEVEL_7 = 'has cast a contaminated spell of 7th level',
    DELIRIUM_HEART = 'visited the *Delirium Heart*',
    FORCED_EVOLUTION = 'knows the forced evolution spell',
    NEUTRALIZING_FIELD = 'knows the Neutralizing Field spell',
    PURGE_CONTAMINATION = 'knows the purge contamination spell',
    SUMMON_DELERIUM_ELEMENTAL = 'knows the summon delerium elemental spell',
    AQUA_EXPURGO = 'created at least 1 dose of aqua expurgo',
    MONSTROUS_TRANFORMATION = 'witnessed monstrous transformation',
    SLAYED_DELERIUM_DRAGON = 'slayed a delerium dragon and examined it',
}

export const achievedPrerequisites = [
    possiblePrerequisites.MONSTROUS_TRANFORMATION,
    possiblePrerequisites.KNOWS_CONTAMINTED_LEVEL_1,
]